version: '3'
services:
  wp:
    build: .
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: host.docker.internal:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: champl00
      WORDPRESS_DB_NAME: wordpress_docker
      WORDPRESS_DB_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
